# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'build-stage'
    ports:
    - '8080:80'
    volumes:
    - '.:/src'
    command: /bin/sh -c "yarn serve"